services:
  - type: web
    name: signspeaks
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install --only-binary=:all: numpy==1.23.5
      pip install -r requirements.txt
    startCommand: gunicorn web_app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
      - key: PORT
        value: 10000 